voxpupuli/puppet-alternatives

- README.markdown
This rebases #22 to omit the provider changes and update the documentation.
> Adding some alternative_entry documentation

- .travis.yml
- CHANGELOG.md
- metadata.json
> release 1.0.0

- .gitignore
- .msync.yml
- .rubocop.yml
- Gemfile
- spec/acceptance/nodesets/docker/centos-5.yml
- spec/acceptance/nodesets/docker/centos-6.yml
- spec/acceptance/nodesets/docker/centos-7.yml
- spec/acceptance/nodesets/docker/debian-7.yml
- spec/acceptance/nodesets/docker/debian-8.yml
- spec/acceptance/nodesets/docker/ubuntu-12.04.yml
- spec/acceptance/nodesets/docker/ubuntu-14.04.yml
- spec/acceptance/nodesets/docker/ubuntu-16.04.yml
> modulesync 0.15.0

- CHANGELOG.md
- README.md
- metadata.json
> Release 1.0.2

- .msync.yml
- .rubocop.yml
- .travis.yml
- Gemfile
> Modulesync

- .msync.yml
- .rubocop.yml
- .travis.yml
- CHANGELOG.md
- metadata.json
> modulesync 0.16.11 & Release 1.1.0

- .github/CONTRIBUTING.md
- .msync.yml
- .rubocop.yml
- .travis.yml
- Gemfile
- Rakefile
- spec/acceptance/nodesets/docker/debian-7.yml
- spec/acceptance/nodesets/docker/debian-9.yml
> modulesync 1.4.1

- metadata.json
Puppet 5 is already in the Travis CI test matrix
> Add support for Puppet 5

- .github/CONTRIBUTING.md
- .msync.yml
- .travis.yml
- Gemfile
> modulesync 1.9.2

- lib/puppet/provider/alternatives/rpm.rb
Fix detection of mode for rpm provider.
Resolves #80
> Fix mode detection for rpm provider

- .msync.yml
- Dockerfile
- Gemfile
- Rakefile
> modulesync 2.7.0

- .github/CONTRIBUTING.md
- .msync.yml
- Gemfile
> modulesync 2.8.0

- .travis.yml
- Dockerfile
- Gemfile
- Rakefile
> modulesync 2.9.0

- metadata.json
> add Debian working versions to metadata

- .msync.yml
- .rubocop.yml
- .travis.yml
- Gemfile
- Rakefile
- lib/puppet/provider/alternative_entry/dpkg.rb
- lib/puppet/provider/alternatives/dpkg.rb
> modulesync 2.10.0

- .github/CONTRIBUTING.md
- .msync.yml
- .rubocop.yml
- Gemfile
- Rakefile
- lib/puppet/provider/alternative_entry/dpkg.rb
- lib/puppet/provider/alternatives/dpkg.rb
> modulesync 2.12.0

- metadata.json
This PR also include:
* #112 
* #113 
* #114
> Add support for Debian 11, Ubuntu 18.04 and 20.04

- metadata.json
> Drop support for Debian 8, 9; RedHat 6 and derivatives (EOL)

- metadata.json
> Drop support for Puppet 5 (EOL)

- .msync.yml
- .puppet-lint.rc
- .sync.yml
- Gemfile
- Rakefile
- lib/puppet/provider/alternative_entry/chkconfig.rb
- lib/puppet/provider/alternative_entry/dpkg.rb
- lib/puppet/provider/alternatives/chkconfig.rb
- lib/puppet/provider/alternatives/dpkg.rb
- lib/puppet/type/alternative_entry.rb
- lib/puppet/type/alternatives.rb
- spec/spec_helper.rb
- spec/unit/provider/alternatives/chkconfig_spec.rb
- spec/unit/provider/alternatives/dpkg_spec.rb
- spec/unit/type/alternatives_spec.rb
> modulesync 5.1.0

- metadata.json
> Add CentOS 8 support

- lib/puppet/provider/alternatives/chkconfig.rb
Fixes multiple expressions in case statement
Fixes #123
> Fixes multiple expressions in case statement

- .msync.yml
- Gemfile
> Update from voxpupuli modulesync_config

- metadata.json
> Add AlmaLinux and Rocky support

- metadata.json
> add EL9 support

- .github/CONTRIBUTING.md
- .github/labeler.yml
- .github/release.yml
- .github/workflows/labeler.yml
- .github/workflows/release.yml
- .msync.yml
- .puppet-lint.rc
- Gemfile
> modulesync 9.1.0

- .github/workflows/ci.yml
- .github/workflows/labeler.yml
- .github/workflows/release.yml
- .msync.yml
- .pmtignore
- Gemfile
- metadata.json
> Drop EoL CentOS 8 support

- lib/puppet/provider/alternative_entry/chkconfig.rb
- lib/puppet/provider/alternative_entry/dpkg.rb
- lib/puppet/provider/alternatives/chkconfig.rb
- lib/puppet/provider/alternatives/dpkg.rb
- lib/puppet/type/alternatives.rb
- spec/unit/type/alternatives_spec.rb
> switch from legacy to structured facts

- .msync.yml
- .sync.yml
- Gemfile
- Rakefile
- metadata.json
- spec/spec_helper.rb
> Add Debian 13 support

- metadata.json
> Drop Puppet support; Drop OpenVox 7 support
